#pragma once

// Global
#define MAX_POWER 127
#define POWER_TO_VOLTAGE (12000/127)
#define VOLTAGE_TO_POWER (127/12000)

// Drive
#define LEFT_PORT_0 -16
#define LEFT_PORT_1 -17
#define LEFT_PORT_2 -18
#define LEFT_PORT_3 -19
#define LEFT_PORT_4 20

#define RIGHT_PORT_0 11
#define RIGHT_PORT_1 -12
#define RIGHT_PORT_2 13
#define RIGHT_PORT_3 14
#define RIGHT_PORT_4 15

#define LEFT_DRIVE_PORTS  {LEFT_PORT_0, LEFT_PORT_1, LEFT_PORT_2, LEFT_PORT_3, LEFT_PORT_4}
#define RIGHT_DRIVE_PORTS {RIGHT_PORT_0, RIGHT_PORT_1, RIGHT_PORT_2, RIGHT_PORT_3, RIGHT_PORT_4}

#define IMU_PORT 16
#define LEFT_MULTIPLIER 1.0
#define RIGHT_MULTIPLIER 1.0
#define DRIVE_SPEED_MULTIPLIER 0.95
#define TURN_SPEED_MULTIPLIER 0.7
#define PRECISION_MULTIPLIER 0.35

// Drive auto
#define DRIVE_UNIT_MULTIPLIER 38.811042613
// #define DRIVE_DEG_MULTIPLIER 3.856
#define DRIVE_DEG_MULTIPLIER 0.87125

#define DRIVE_TURN_MULTIPLIER 1.00
#define TRACK_WIDTH 12.23

// Intake
#define INTAKE_PORT -10
#define INTAKE_SPEED 127
#define OUTTAKE_SPEED 63

// Conveyor
#define CONVEYOR_PORTS {-2, 9}
#define CONVEYOR_FORWARD_SPEED 127
#define CONVEYOR_REVERSE_SPEED 63

// Goal Grabber
#define GOAL_GRABBER_PORT 'H'

// Arm
#define ARM_PORT0 'B'
#define ARM_PORT1 'C'

// Sensors
#define COLOR_SENSOR_TOLERANCE 10 // needs testing
#define COLOR_SENSOR_PORT 42 // CHANGEME

// Unused
// #define FRONT_RIGHT_DRIVE_PORTS { 19,  20}
// #define FRONT_LEFT_DRIVE_PORTS  {-11, -12}
// #define REAR_RIGHT_DRIVE_PORTS  { 17,  18}
// #define REAR_LEFT_DRIVE_PORTS   {-13, -14}